# Generated by Django 4.2.7 on 2023-11-30 18:21

import apps.proveedor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_proveedor',
            name='presentacion',
            field=models.FileField(blank=True, max_length=250, null=True, upload_to='document', verbose_name='Presentación'),
        ),
        migrations.AlterField(
            model_name='m_tipo',
            name='nombre',
            field=apps.proveedor.models.UpperCharField(max_length=150, null=True, verbose_name='Nombre'),
        ),
    ]
